name: Publish package to the Maven Central Repository
on:
  push:
    branches: [publish]
jobs:
  publish:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Import GPG key
        run: |
          echo "${{ secrets.MAVEN_GPG_PRIVATE_KEY }}" | base64 --decode > private-key.gpg
          gpg --batch --yes --passphrase "${{ secrets.GPG_PASSPHRASE }}" --import private-key.gpg

      - name: Debug GPG
        run: |
          gpg --version
          gpg --list-keys

      - name: Set up Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: ossrh
          server-username: ${{ secrets.OSSRH_USERNAME }}
          server-password: ${{ secrets.OSSRH_TOKEN }}
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }} # Value of the GPG private key to import
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }} # env variable for GPG private key passphrase

      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
